### PR TITLE
Try fix unexpected index calculation

### PR DESCRIPTION
**Pull request by Sieluna**
I feel that the slot boundary calculation is a bit wired. I am not sure that I fixed the issue correctly.

### CODE REVIEW

**Comment by Sieluna** [comment]
Exception is fine now, but the problem has not been solved, it has become a random increase. XD . . I might need to spend some time figuring out what's wrong. Do you have any suggestion?

**Comment by Sieluna** [comment]
Oder the debug info by GPT:
[0-9]A remainingCount: 9, slotCount: 25, hostIndex: 0, slotIndex: (0, 9)
[9-18]A remainingCount: 9, slotCount: 25, hostIndex: 0, slotIndex: (9, 18)
[18-27]B remainingCount: 9, slotCount: 25, hostIndex: 0, slotIndex: (18, 24)
[18-27]A remainingCount: 2, slotCount: 25, hostIndex: 1, slotIndex: (0, 2)
[27-36]A remainingCount: 9, slotCount: 25, hostIndex: 1, slotIndex: (2, 11)
[36-44]A remainingCount: 8, slotCount: 25, hostIndex: 1, slotIndex: (11, 19)
[44-52]B remainingCount: 8, slotCount: 25, hostIndex: 1, slotIndex: (19, 24)
[44-52]A remainingCount: 2, slotCount: 25, hostIndex: 2, slotIndex: (0, 2)
[52-60]A remainingCount: 8, slotCount: 25, hostIndex: 2, slotIndex: (2, 10)
[60-68]A remainingCount: 8, slotCount: 25, hostIndex: 2, slotIndex: (10, 18)
[68-76]B remainingCount: 8, slotCount: 25, hostIndex: 2, slotIndex: (18, 24)
[68-76]A remainingCount: 1, slotCount: 25, hostIndex: 3, slotIndex: (0, 1)
[76-84]A remainingCount: 8, slotCount: 25, hostIndex: 3, slotIndex: (1, 9)
[84-92]A remainingCount: 8, slotCount: 25, hostIndex: 3, slotIndex: (9, 17)
[92-100]B remainingCount: 8, slotCount: 25, hostIndex: 3, slotIndex: (17, 24)

**Comment by Sieluna** [comment]
I guess padding disrupts the memory layout:
https://github.com/sicusa/Sia.NET/blob/c71a9bceb87054facb5f28765dbafd5323460aca/Sia/Entities/Extensions/EntityQueryExtensions.ForEach.cs#L116-L134

**Comment by sicusa** [comment]
fixed by fa4cb73a98c7ba62a40c500ff8e7da43f2138334

**Pull request closed without merging**
